// ObjectWindows - (C) Copyright 1992 by Borland International

#ifndef _CHECKERS_H
#define _CHECKERS_H

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#define CM_UNDO         24341
#define CM_SEARCHDEPTH  24342
#define CM_AUTO         24343
#define CM_ITERATE      24344
#define CM_KILLER       24345
#define CM_ABOUT        24346
#define CM_REDO         24347
#define CM_MOVE         24348
#define CM_STOP         24349
#define CM_LOG          24350
#define IDM_EXIT        24351

enum SIDE {Black, Red, Unknown };


#endif  // _CHECKERS_H

