// (C) Copyright 1991, 1992 by Borland International

#define Id_Splash	102
#define bmp_StatusBar	101
#define dlg_Directories	112
#define  cm_Open                       102
#define  cm_All                        121
#define  cm_Some                       122
#define  cm_By                         123
#define  cm_Index                      141
#define  cm_Topic_Search               142
#define  cm_Glossary                   143
#define  cm_Using_Help                 144
#define  cm_About_CUA                  145
#define  cm_Directories                151
#define  cm_Preferences                152
#define  cm_Mouse                      153
#define  cm_Options_Open               154
#define  cm_Options_Save               155
#define  cm_Options_SaveAs             156
#define  id_open1                      100
#define  id_open2                      101
#define  Id_File_list                  102
#define  id_Dir_list                   103
#define  id_Ok                           1
#define  id_cancel                       2
#define  id_help                       210
#define  id_Copies                     211
#define  id_all                        212
#define  id_Partial                    213
#define  id_From                       214
#define  id_To                         215
#define  id_printer                    216
#define  id_Print                      217
#define  id_Printer_setup              218
#define  ID_CUA_Directory              219
#define  id_Include_Directory          220
#define  id_Library_Directory          221
#define  id_none                       222
#define  id_current_directory          223
#define  id_config_file_directory      224
#define  id_Editor_files               225
#define  id_Environment                226
#define  id_Desktop                    227
#define  id_nothing                    228
#define  id_TopicSearch                229
#define  id_Process_it                 230
#define  id_horiz_scoller              231
#define  id_Reverse_mouse_buttons      232
#define  id_Graph                      207
#define  id_Scribble                   206
#define  id_Text                       205
#define  id_ClearWindow                229
#define  id_InverseColor               230
#define  id_FName                      100
#define  id_FList                      101
#define  id_DList                      102
#define  id_FPath                      103
#define  id_Graphics  231
#define  dlg_Open                      100
#define  dlg_SaveAs                    101
#define  dlg_Print                     102
#define  dlg_Preferences               103
#define  dlg_About                     104
#define  dlg_MouseDialog               105
#define  dlg_Mouse                     105
#define  dlg_FileNew                   106
#define  dlg_Options_Open              107
#define  dlg_Options_SaveAs            108
#define  sth_Open                        2
#define  sth_Save                        3
#define  sth_SaveAs                      4
#define  sth_Print                       5
#define  sth_Options_Open                6
#define	sth_File		8
#define	sth_Edit		15
#define	sth_View		19
#define	sth_Option		25
#define	sth_Window		33
#define	sth_Help		40
#define  sth_Mouse                      13
#define  sth_Preferences                14
#define  bmp_StatusLine                100
#define  men_Main                      100
#define  acc_Main                      100
#define  ico_RWCDemo                   100
#define  cm_New                        100
#define  cm_Save                       103
#define  cm_SaveAs                     104
#define  cm_Exit                       106
#define  cm_Undo                       200
#define  cm_Cut                        201
#define  cm_Copy                       202
#define  cm_Paste                      203
#define  cm_Clear                      204
#define  cm_Delete                     205
#define	cm_Tile		7
#define  cm_ArrangeIcons               161
#define  cm_Cascade                    162
#define  cm_CloseAll                   163
#define	sth_FileNew		1
#define	sth_FileOpen		2
#define	sth_FileSave		3
#define	sth_FileSaveAs		4
#define	sth_FilePrint		5
#define	sth_FileExit		100
#define	sth_EditUndo		9
#define	sth_EditCut		10
#define	sth_EditCopy		11
#define	sth_EditPaste		12
#define	sth_EditClear		13
#define	sth_EditDelete		14
#define	sth_ViewAll		16
#define	sth_ViewSome		17
#define	sth_ViewBy		18
#define	sth_OptionsDirectory		20
#define	sth_OptionsEnvironment		21
#define	sth_OptionsOpen		22
#define	sth_OptionsSave		23
#define	sth_OptionsSaveAs		24
#define	sth_EnvironmentPreferences		26
#define	sth_EnvironmentMouse		27
#define	sth_WindowTile		28
#define	sth_WindowCascade		29
#define	sth_WindowArrange		30
#define	sth_WindowIcon		31
#define	sth_WindowCloseAll		32
#define	sth_HelpIndex		34
#define	sth_HelpTopic		35
#define	sth_HelpSearch		36
#define	sth_HelpGlossary		37
#define	sth_HelpUsing		38
#define	sth_HelpAbout		39
#define	cm_Print		105
#define  ScribbleWindow  100
#define  FileWindow  101
#define  GraphWindow  102
#define	ID_ScribbleDirectory		219
#define	id_TextDirectory		220
#define	id_GraphicDirectory		221

