#
# ObjectWindows - (C) Copyright 1992 by Borland International
#

!if !$d(BCROOT)
!include "..\bcroot.inc"
!endif

!include "..\makefile.inc"

fileapp.exe: turboc.cfg fileapp.obj fileapp.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) fileapp,fileapp,,@&&!
$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     $(RC) -30 -K fileapp.res fileapp.exe

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
        del turboc.cfg

