#
# ObjectWindows - (C) Copyright 1992 by Borland International
#

!if !$d(BCROOT)
!include "..\bcroot.inc"
!endif

!include "..\makefile.inc"

calc.exe: turboc.cfg calc.obj calc.res
     $(TLINK)  $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) calc,calc,,@&&!
$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     $(RC) -30 -K calc.res calc.exe

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
        del turboc.cfg

