#include<stdio.h>
int main(void)
{
    unsigned int num;
    int count;
    while(scanf("%u", &num) != EOF)
    {
        count = 0;
        printf("Hailstone generated by %d:\n", num);
        while(num != 1)
        {
            printf("%d ", num);
            if(num%2)
                num = num * 3 + 1;
            else
                num /= 2;
            count++;
        }
        printf("1\nNumber of hailstone generated:%d\n\n", count+1);
    }
    return 0;
}
